Separate image ingestion from main pipeline run
askap-vast/vast-pipeline pull request #544
Opened 2021-06-03 05:20 UTC by dliptai

2021-06-03 06:32 UTC, dliptai commented
Note: this does not address all the features discussed/requested in #375 , but it does lay the foundation for most of them.

Currently this "new feature" is backwards compatible, since you still run the pipeline in the same was as before (i.e. the config format is unchanged).

Ideally we'd want to clean things up and completely split off the four options:
- condon_errors
- selavy_local_rms_fill_value
- ra_uncertainty
- dec_uncertainty
from the main config file.

I'll leave the removal of `selavy_local_rms_fill_value` (and using values from the noisemap instead) to another pull request.

For the time being it would be nice to merge what we have, and address each of the above points in new, smaller, pull requests.

2021-06-04 10:55 UTC, ajstewart requested changes
I will continue to test and review the code changes but a few comments:
* There are no documentation updates included, are they intended to be in a separate PR? I think it might be good to include them along with the code changes (especially for changes like this to the running) as it also helps with the reviewing. From the top of my head I think this will mean writing a new section for the command and a new page for how to use the separated ingest image feature along with edits to the 'how to run' section where needed.
* Update `CHANGELOG`.
* More of a question - has the UI process been thought about? With v1.0.0, as long as the user has uploaded the images to the right location they can set up and run a pipeline run purely through the UI (useful for instances like on Nimbus where users don't have access to the CLI). From what I can see I think if the run meets an image that hasn't been ingested it just ingests it - is that correct? As we're now using the `dev` branch workflow I don't think this is immediately required but it might need some clear 'to do' comments or an issue created after this has been merged.

2021-06-08 06:03 UTC, dliptai commented
@ajstewart agreed on the docs. I'll update those, and the changelog.

I have not thought about how to incorporate this into the UI. Aside from implementing it in a manner that preservers the current UI behaviour. So yes, if the run meets an image it hasn't ingested previously, it ingests it.

2021-06-09 21:29 UTC, marxide requested changes
Thanks! I've requested one change that we catch any validation errors and wrap it in the appropriate Django exception.

I'm also not sure if we need the `source_monitoring` config for the image ingest.

Other than that, looks good to me.

2021-06-09 21:29 UTC, marxide commented on vast_pipeline/management/commands/ingestimages.py
> +from django.core.management.base import BaseCommand
```suggestion
from django.core.management.base import BaseCommand, CommandError
```

see suggestion below

2021-06-09 21:29 UTC, marxide commented on vast_pipeline/management/commands/ingestimages.py
> +        image_config.validate()
I think we should catch the validation error and raise a `CommandError` as Django expects.

```suggestion
    try:
        image_config.validate()
    except PipelineConfigError as e:
        raise CommandError(e)
```

2021-06-09 21:29 UTC, marxide commented on vast_pipeline/pipeline/config.py
> +            "source_monitoring": yaml.Map({"monitor": yaml.Bool()}),
It doesn't look like we need this in the ingest config. If not, might need to remove it here and also in the Jinja template.

2021-06-21 09:35 UTC, dliptai commented on vast_pipeline/pipeline/config.py
> +            "source_monitoring": yaml.Map({"monitor": yaml.Bool()}),
It turns out we "sort of" need it. The validation step does some checks if source monitoring is on. I decided to just catch the key error and then set monitoring to False

2021-06-23 18:36 UTC, marxide requested changes
After fixing the broken docs link, looks good to me!

2021-06-23 18:36 UTC, marxide commented on docs/using/ingestimages.md
> +Administrators can refer to the [`ingestimages`](../adminusage/cli/#ingestimages) command for details on how to ingest images.
```suggestion
Administrators can refer to the [`ingestimages`](../../adminusage/cli/#ingestimages) command for details on how to ingest images.
```

2021-06-24 15:58 UTC, ajstewart requested changes
I got around to testing it and it works great, thanks! I have some further comments that are mainly on the documentation.

2021-06-24 15:58 UTC, ajstewart commented on docs/using/ingestimages.md
> +# Adding images to the database
I think it would be good to see this page expanded slightly to include a description of the configuration file for the command (see the `Run Configuration` page for what I mean). I don't think it needs a full example, as we haven't done for others but the config should be explained here. I think the entries could be copied from this page - then the work is done ready for when those options are(/if) eventually removed from the main processing file.

2021-06-24 15:58 UTC, ajstewart commented on docs/using/ingestimages.md
> +Administrators have the added option of ingesting new images via the command line, without running the full pipeline.
```suggestion
Administrators have the added option of ingesting new images via the command line, without running the full pipeline.

!!! note
    Currently, when non-admin users run the pipeline, any images listed in the configuration that do not exist in the database will be processed and uploaded to the database. Hence, it is not a requirement to ingest images using this process before a run is processed that uses new images.

```

2021-06-24 15:58 UTC, ajstewart commented on docs/using/ingestimages.md
> +Administrators have the added option of ingesting new images via the command line, without running the full pipeline.
Just swapping the order of these statements.

2021-06-24 15:58 UTC, ajstewart commented on templates/generic_table.html
> +                    "Base astrometric RA uncertainty in arcseconds that will be added in quadrature to the fitting uncertainties. (NOTE: only applied to NEW images that are not already present in the
```suggestion
                    "Base astrometric RA uncertainty in arcseconds that will be added in quadrature to the fitting uncertainties. <b>Note</b> that this is only applied to <b>new</b> images that are not already present in the database, and to forced extractions."
```

2021-06-24 15:58 UTC, ajstewart commented on templates/generic_table.html
> +                    "Base astrometric RA uncertainty in arcseconds that will be added in quadrature to the fitting uncertainties. (NOTE: only applied to NEW images that are not already present in the
I think that the note is important enough to leave out the brackets. If you agree then this should be applied to the other notes in the file.

2021-06-24 15:58 UTC, ajstewart commented on vast_pipeline/image/main.py
> +        config (Dict): The image configuration settings.
Just checking as I can't see the full code through this review - is this a Dict of one of the nearly-Dict YAML loaded objects?

2021-06-24 15:58 UTC, ajstewart commented on docs/adminusage/cli.md
> +
I know it's not consistent with this in this doc file but an example output would be nice, which some other commands have.

2021-06-24 15:58 UTC, ajstewart commented on docs/adminusage/cli.md
> +
See example output comment above.

2021-06-24 15:58 UTC, ajstewart commented on vast_pipeline/management/commands/initingest.py
> +            f.write(template_str+"\n")
Perhaps this file should force the file extension to be `.yaml`.

2021-06-24 15:58 UTC, ajstewart commented on vast_pipeline/management/commands/initingest.py
> +            f.write(template_str+"\n")
Also a second comment on this command.

The template that the `initingest` command produces has the background category commented out. I know that @marxide fixed this for the main config template writing (is that right?).

```
  selavy:
  # list input selavy catalogues here, as above with the images

  noise:
  # list input noise (rms) images here, as above with the images

  # Required only if source_monitoring.monitor is true, otherwise optional. If not providing
  # background images, remove the entire background section below.
  # background:
  # list input background images here, as above with the images
```

2021-06-25 05:50 UTC, dliptai commented on mkdocs.yml
> +    - Adding new Images: using/ingestimages.md
Agreed. Should we also move the section `Deleting a Pipeline` to `Admin Usage`? Currently it sits under `Using the Pipeline`

2021-06-25 06:32 UTC, dliptai commented on vast_pipeline/management/commands/initingest.py
> +            f.write(template_str+"\n")
Yep it does (but not for epoch mode)

2021-06-25 06:40 UTC, dliptai commented on vast_pipeline/image/main.py
> +        config (Dict): The image configuration settings.
It's a Dict, purely to keep things simple since the `SelavyImage` class now only depends on the the subset of options that make up the image ingestion config.

But I could try set up something to convert a `PipelineConfig` object into a `ImageIngestConfig` object...?

2021-06-25 10:04 UTC, ajstewart commented on mkdocs.yml
> +    - Adding new Images: using/ingestimages.md
I think the `Deleting a Pipeline` is ok as that's a common task that users may want to do so that page at least explains that they need to get an admin to do it. Eventually users should be able to delete their own run through the UI.

2021-06-25 10:05 UTC, ajstewart commented on vast_pipeline/image/main.py
> +        config (Dict): The image configuration settings.
That's fine, I just wondered as I got caught out with one config yaml object thinking it was a Dict when it wasn't.

2021-06-25 11:01 UTC, ajstewart commented on vast_pipeline/management/commands/initingest.py
> +            f.write(template_str+"\n")
Ah yeah apologies I mis-remembered what the issues was. Previously the heading wasn't appearing at all, so this behaviour is in line with how it currently is.

2021-06-25 15:17 UTC, ajstewart approved these changes
Looking through the latest changes I think this is now good to go!

2021-06-28 02:56 UTC, merged