Fix noise image statistics
askap-vast/vast-pipeline pull request #755
Opened 2024-09-25 00:26 UTC by mauch

Check for negative pixes as well as 0 or NaN ones in the noise images when calculating statistics.

This fixes #753

2024-09-25 06:14 UTC, ddobie requested changes

2024-09-25 06:14 UTC, ddobie commented on CHANGELOG.md
> +- Fixed noise image statistics [#755](https://github.com/askap-vast/vast-pipeline/pull/755)
```suggestion
- Fixed handling of NaNs and negatives in noise image statistics [#755](https://github.com/askap-vast/vast-pipeline/pull/755)
```

2024-09-25 06:14 UTC, ddobie commented on CHANGELOG.md
> +- [#755](https://github.com/askap-vast/vast-pipeline/pull/755): fix: Fixed noise image statistics
```suggestion
- [#755](https://github.com/askap-vast/vast-pipeline/pull/755): fix: Fixed handling of NaNs and negatives in noise image statistics
```

2024-09-25 06:14 UTC, ddobie commented on vast_pipeline/pipeline/utils.py
> +    logger.debug('Image RMS Min: %.3g Max: %.3g Median: %.3g', min_val, max_val, med_val)
```suggestion
    logger.debug(f"Image RMS Min: {min_val:.3g} Max: {max_val:.3g} Median: {med_val:.3g}")
```

2024-09-30 00:11 UTC, mauch commented on vast_pipeline/pipeline/utils.py
> +    logger.debug('Image RMS Min: %.3g Max: %.3g Median: %.3g', min_val, max_val, med_val)
I actually did the formatting my way since its considered bad practice to use f-strings in log messages fow now. Both because f-strings are greedy and will compute no matter what log-level you have set (i.e. if you set INFO logging, python will still format the DEBUG log strings even though nothing is printed to the screen - the 'old-style' way will not do this) and because there is apparently a security vulnerability associated with f-strings in logs (see https://discuss.python.org/t/safer-logging-methods-for-f-strings-and-new-style-formatting/13802 for some discussion).

These are both really micro-optimisations and probably not important at all, however I'm brow-beaten from working with software engineers for a decade so can't help but mention it:)

I'm happy to change it to your suggestion but I just thought I'd let you know the reson I did it my way. Let me know what you think.

2024-09-30 10:54 UTC, ddobie commented on vast_pipeline/pipeline/utils.py
> +    logger.debug('Image RMS Min: %.3g Max: %.3g Median: %.3g', min_val, max_val, med_val)
Ah I had no idea! Happy for you to leave it your way then

2024-09-30 10:54 UTC, ddobie approved these changes

2024-10-01 02:48 UTC, merged